apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: nififns.nififn.b23.io
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.flow
    description: The UUID of the Flow in NiFi-Registry
    name: Flow
    type: string
  - JSONPath: .spec.flowVersion
    description: The version of the NiFiFlow
    name: Version
    type: integer
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  group: nififn.b23.io
  names:
    kind: NiFiFn
    plural: nififns
    shortNames:
    - nifn
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            bucket:
              maxLength: 36
              minLength: 36
              type: string
            flow:
              maxLength: 36
              minLength: 36
              type: string
            flowFiles:
              items:
                type: string
              minItems: 1
              type: array
            flowVersion:
              format: int32
              minimum: -1
              type: integer
            image:
              pattern: .+:.+
              type: string
            registryUrl:
              type: string
          required:
          - registryUrl
          - bucket
          - flow
          - flowVersion
          - flowFiles
          - image
          type: object
        status:
          properties:
            flow:
              type: string
          required:
          - flow
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
