kind: Service
apiVersion: v1
metadata:
  name: nifi-service
  namespace: system
spec:
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 90
  selector:
    app: nifi
  ports:
  - port: 8081
    targetPort: nifi-http
