apiVersion: v1
kind: Service
metadata:
  name: registry-service
  namespace: system
spec:
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 90
  selector:
    app: nifi
  ports:
  - port: 18080
    targetPort: registry-http
