apiVersion: nififn.b23.io/v1alpha1
kind: NiFiFn
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: nififn-sample
  namespace: nifi-fn-operator-system
spec:
  image: "samhjelmfelt/nifi-fn:latest"
  registryUrl: "http://registry-service:18080"
  bucket: "703b95c2-ad6b-4c3c-aa20-af634a964d2c"
  flow: "92a849c8-3ed3-413d-a360-9d474f999a42"
  flowVersion: -1
  flowFiles:
  - "absolute.path-/path/to/input/data/;filename-testfile.txt"
