apiVersion: v1
kind: Service
metadata:
  name: nifi-service
  namespace: nifi-stateless-operator-system
spec:
  ports:
  - port: 8081
    targetPort: nifi-http
  selector:
    app: nifi
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 90
---
apiVersion: v1
kind: Service
metadata:
  name: registry-service
  namespace: nifi-stateless-operator-system
spec:
  ports:
  - port: 18080
    targetPort: registry-http
  selector:
    app: nifi
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 90
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: nifi
  name: nifi
  namespace: nifi-stateless-operator-system
spec:
  selector:
    matchLabels:
      app: nifi
  serviceName: nifi-service
  template:
    metadata:
      labels:
        app: nifi
    spec:
      containers:
      - env:
        - name: NIFI_WEB_HTTP_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: NIFI_WEB_HTTP_PORT
          value: "8081"
        image: dbkegley/nifi:1.9.2
        imagePullPolicy: Always
        name: nifi
        ports:
        - containerPort: 8081
          name: nifi-http
      - env:
        - name: NIFI_REGISTRY_WEB_HTTP_HOST
          value: 0.0.0.0
        - name: NIFI_REGISTRY_WEB_HTTP_PORT
          value: "18080"
        image: apache/nifi-registry:0.3.0
        imagePullPolicy: Always
        name: nifi-registry
        ports:
        - containerPort: 18080
          name: registry-http
